name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}
    env:
      SUPABASE_AUTH_URL: ${{ vars.SUPABASE_AUTH_URL }}
      SUPABASE_API_KEY: ${{ vars.SUPABASE_API_KEY }}
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      SUPABASE_DIRECT_URL: ${{ vars.SUPABASE_DIRECT_URL }}
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
      ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
      
    strategy:
        matrix:
            node-version: ['20.x']

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }} 
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file for tests
        run: |
          cat > .env << EOF
          SUPABASE_URL=${{ env.SUPABASE_URL }}
          SUPABASE_DIRECT_URL=${{ env.SUPABASE_DIRECT_URL }}
          SUPABASE_AUTH_URL=${{ env.SUPABASE_AUTH_URL }}
          SUPABASE_API_KEY=${{ env.SUPABASE_API_KEY }}
          DATABASE_URL=${{ env.DATABASE_URL }}
          EOF

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run database migrations
        run: npx prisma migrate deploy

      - name: Run unit tests
        run: npm run test

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Build application
        run: npm run build

  security:
    runs-on: ubuntu-latest
    needs: test
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}
    
    strategy:
        matrix:
            node-version: ['20.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level moderate

    #   - name: Run Snyk security scan
    #     uses: snyk/actions/node@master
    #     env:
    #       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #     with:
    #       args: --severity-threshold=high

  code-quality:
    runs-on: ubuntu-latest
    needs: test
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}
    
    strategy:
        matrix:
            node-version: ['20.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: npx prettier --check "src/**/*.ts" "test/**/*.ts"

      - name: Run ESLint
        run: npm run lint

      - name: Check TypeScript compilation
        run: npx tsc --noEmit

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate 