name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: 'Development' 
    
    strategy:
      matrix:
        node-version: ['20.x']
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
            npm ci
            npm install -g dotenv-cli

      - name: Create .env file for tests
        run: |
          cat > .env << EOF
          SUPABASE_URL=postgresql://postgres:postgres@localhost:5432/test_db
          SUPABASE_DIRECT_URL=postgresql://postgres:postgres@localhost:5432/test_db
          SUPABASE_AUTH_URL=${{ secrets.SUPABASE_AUTH_URL }}
          SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }}
          EOF

      - name: Generate Prisma client
        run: |
            npm run prisma:generate
            
      - name: Run database migrations
        run: |
            npm run prisma:migrate:deploy

      - name: Run database seed
        run: |
            npm run prisma:seed:up

      - name: Run unit tests
        run: npm run test

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Build application
        run: npm run build

